"""empty message

Revision ID: 4cad56241295
Revises: d4e32d2b97fe
Create Date: 2022-03-22 09:57:05.031855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cad56241295'
down_revision = 'd4e32d2b97fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('longtitude', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('income_range', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('voter_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('restriction', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['public.category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restriction'], ['public.voter_list.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('voter_list_member',
    sa.Column('voter_list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_list_id'], ['public.voter_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voter_list_id', 'user_id'),
    schema='public'
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['public.poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('vote',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['public.answer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['public.poll.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'poll_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote', schema='public')
    op.drop_table('answer', schema='public')
    op.drop_table('voter_list_member', schema='public')
    op.drop_table('poll', schema='public')
    op.drop_table('voter_list', schema='public')
    op.drop_table('user', schema='public')
    op.drop_table('category', schema='public')
    # ### end Alembic commands ###
