"""empty message

Revision ID: 93d49d063ec4
Revises: 39fc678171cd
Create Date: 2022-03-28 17:25:30.520411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d49d063ec4'
down_revision = '39fc678171cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_poll_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'poll', ['poll_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('poll_user_id_fkey', 'poll', type_='foreignkey')
    op.create_foreign_key(None, 'poll', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('vote_poll_id_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_answer_id_fkey', 'vote', type_='foreignkey')
    op.drop_constraint('vote_user_id_fkey', 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'poll', ['poll_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'answer', ['answer_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('voter_list_user_id_fkey', 'voter_list', type_='foreignkey')
    op.create_foreign_key(None, 'voter_list', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('voter_list_member_voter_list_id_fkey', 'voter_list_member', type_='foreignkey')
    op.drop_constraint('voter_list_member_user_id_fkey', 'voter_list_member', type_='foreignkey')
    op.create_foreign_key(None, 'voter_list_member', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'voter_list_member', 'voter_list', ['voter_list_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('voter_list_poll_poll_id_fkey', 'voter_list_poll', type_='foreignkey')
    op.drop_constraint('voter_list_poll_voter_list_id_fkey', 'voter_list_poll', type_='foreignkey')
    op.create_foreign_key(None, 'voter_list_poll', 'voter_list', ['voter_list_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'voter_list_poll', 'poll', ['poll_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voter_list_poll', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'voter_list_poll', schema='public', type_='foreignkey')
    op.create_foreign_key('voter_list_poll_voter_list_id_fkey', 'voter_list_poll', 'voter_list', ['voter_list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('voter_list_poll_poll_id_fkey', 'voter_list_poll', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'voter_list_member', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'voter_list_member', schema='public', type_='foreignkey')
    op.create_foreign_key('voter_list_member_user_id_fkey', 'voter_list_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('voter_list_member_voter_list_id_fkey', 'voter_list_member', 'voter_list', ['voter_list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'voter_list', schema='public', type_='foreignkey')
    op.create_foreign_key('voter_list_user_id_fkey', 'voter_list', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'vote', schema='public', type_='foreignkey')
    op.create_foreign_key('vote_user_id_fkey', 'vote', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('vote_answer_id_fkey', 'vote', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('vote_poll_id_fkey', 'vote', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'poll', schema='public', type_='foreignkey')
    op.create_foreign_key('poll_user_id_fkey', 'poll', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'answer', schema='public', type_='foreignkey')
    op.create_foreign_key('answer_poll_id_fkey', 'answer', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
